### ISSUE TITLE
Minor Comment Issue in file tests/hello_ctc2a.asm

### ISSUE THREAD

**Issue by dennowiggle** [Z80-Retro/2063-Z80#18]
tests/hello_ctc2a.asm contains a comment that references the wrong section in the manual.

Line 79 Reads
    ld      a,11000100b ; wr4 = /64 N1 (see UM008101-0601, pdf page 262)
I believe it should be changed to 
    ld      a,11000100b ; wr4 = /64 N1 (see UM008101-0601, page 286-287, [pdf page 306-307])

Ref : In the video "Z80 Retro #16 - Board Testing Pt. VI (Interrupts) at 1:12:30
https://youtu.be/WmhSJg9fJ9U?list=PL3by7evD3F51Cf9QnsAEdgSQ4cz7HQZX5&t=4350

Thanks for creating this series! I'm enjoying following along slowly.

**Comment by johnwinans** [comment]
Good catch!  Yeah.  It looks like 262 is an overview.  The details on the later pages make much more sense in this context.
Thanks!
